// Generated by CIRCT firtool-1.138.0
module TransformExample(
  input         clock,
                reset,
  input  [31:0] source_bits_data,
  input         source_valid,
  output        source_ready,
  output [31:0] sink_bits_data,
  output        sink_valid,
  input         sink_ready
);

  assign source_ready = sink_ready;
  assign sink_bits_data = source_bits_data + 32'h5;
  assign sink_valid = source_valid;
endmodule

